---
- project:
    templates:
      - publish-stx-docs
      - stx-release-notes-jobs
      - stx-bandit-jobs
    check:
      jobs:
        - starlingx-common-tox-linters
        - starlingx-common-tox-pep8
        - clients-tox-bandit
        - clients-tox-coverage
        - clients-tox-linters-trixie
        - clients-tox-pep8-trixie
        - clients-tox-bandit-trixie
        - clients-tox-coverage-trixie
    gate:
      jobs:
        - starlingx-common-tox-linters
        - starlingx-common-tox-pep8
        - clients-tox-bandit
        - clients-tox-coverage
        - clients-tox-linters-trixie
        - clients-tox-pep8-trixie
        - clients-tox-bandit-trixie
        - clients-tox-coverage-trixie
    post:
      jobs:
        - stx-clients-upload-git-mirror

- job:
    name: stx-clients-upload-git-mirror
    parent: upload-git-mirror
    description: >
      Mirrors opendev.org/starlingx/clients to
      github.com/starlingx/clients
    vars:
      git_mirror_repository: starlingx/clients
    secrets:
      - name: git_mirror_credentials
        secret: stx-clients-github-secret3
        pass-to-parent: true

- secret:
    name: stx-clients-github-secret3
    data:
      user: git
      host: github.com
      # yamllint disable-line rule:line-length
      host_key: github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk=
      ssh_key: !encrypted/pkcs1-oaep
        - csJ25B2EiLlOJHieOuL1CNwQ2pmjwwW2Ig+1Uc7HGolXxohWWQQCJb7/buNut6k/u+VSW
          vZQXykBE8k6Z0jhIRE16kJi701OLMnicUTMZHBtMXo4otH4qzAskblR7qFFKVL5bb04Zo
          qShb5OpuLORe6exwRDDnMNeZJiOjZCM2bgTZgHs/6ETRaFZLbg4cGQZ9fGELeVNbIcIWW
          VNbKQjZLmNdhid1BMXa7NTJwSMNXbh8DL9ek4j/g12PvZXfK+jIcXQpzl6V0NpU9a0QPF
          rigaDa/m1aegBqM6e3ydGRa8qhdOI+jnJ5MRch5KCmRI/s1nNM8BZFVPV3e8UNl8lJM/L
          gqOU+okuy9Tp2qdqsKfbEL5WBmVY/GIakOMhWouwXP/BYzoLfrysQ1ksANgortxbGlO9L
          o2ES8NagzQsn739sxQmjreEerdFeqFQZfxj2Z/5UkTUX2WJ3M+L9s1rax5s6MB4OFKPSY
          8GyCrczY8WHwKh+x55Yk6QTbALaw2+zYIbktnwYP4V/ECy+QiUxCeVbihQeE9LBeyEZHC
          EvGrOZJg126Q/xbmzbT5sUvQLVQRdoACjXzc0InxTcrQOcS+I3bmWCkwX32K7BcwhXxIw
          QrHhrjgE+9NM9svlUAWVYCQLMNd+yIhpJ1dbHcVi7S127zoAExY0Atnqqdfp0Y=
        - 09V+ZkDvuV25dvxTuBwJ0eUgsuaRnAirEK4hkxgPbJ+5EwCMrrALQOBHaK8Nlw7WlzE2O
          /xS2wgBPDuWjfpx4Raad3kjC3ootLOy2/ISv3Cx+vbqnlpHyCHiGj4xNnf2+kfNkVFv0N
          0Qq0AU/ilb2rEr0QOG+umvPeYPO77clgkTsqWkyh2/lvqig7oKGHfOBQat5BYGxOpIe63
          jPugty9ahuSfDOFgquBRgDIlmDsipfKFirRMTKzn1Y5E9fC5rUq0/jI4zNq9PcO+KoFLZ
          7VpFNY3W1enGOSePDAElz1L7HNChylesbsP06u5ceMz5+tC9axY+DADLpeQhJd+rdi20d
          vFDPyP0t+MXJtFyZLnZuOlosFRlCgykX3Vg3v1LG83YwFC6VvK+xencrECHItdyWGpPH1
          h9nM6iYjwC7skjEnXmODBQ+ual2Ebwr1ZNjq2qCs9/D59brQlWycpGdeomPhU5EE83CDT
          5+QOYZvGQeEOsk1hwpNc6ke6Pl+JkfPck6mKcLTGza8vaFbwx80yrz1jnfcQBiMQtcH98
          XDbQDVcga8Gc3apCdXYFyE0q93dg8TNhzUwVcO2ekobnxN6fBo4O03oDmYvifoCt4xDGD
          Kznbj2C7efi36DP67xlmtFfTB5JZBRpK7700WVf77iFAPppLA4xy+UTLNyj40o=
        - b0QdS8Nezx/gNxObX1o8DfOoCYvzqgqR8TWYlWS1x7uve5ARZTS96VZq+YRmkGjAPISPI
          WIULlP25LuXmtn4jindRB2i8zJtcQJqLYlxQa/3cbuXppRtJgxoWlNy/Fm0n+hQE5CpwY
          bTFkt01nf8Vi7qbrsqgItqqkv3nDrLHBDAMl7AQ5rJb+TU4Njkg45egUPyhAaXtRbvq20
          e0OFvAl3PrlLLyvfHvCRrPYU/umO19SHnwm3+xAz7MTaJsJ6e9cyEKGL87AouvaoQ7uvQ
          2s+YM4pp5GijejN2vPiTRpBB53dGSDJYgqSKetierbBtjJK+F5lPWd7peNDQMUlUctgZm
          rafQmHKuX0lx+TCjIN1UcCRKh2slBegk1wMOHeVrTkGTzWIdo8m3QWcIWKt+3yJYMQP58
          fnkLkNs8BuPl6wDNVFwfrLlsNqBuOiNal4A998uyQrnE6OnEOiAtBtQlC695AIPuMIVsL
          6qcvPLiB2baajqo8XM9QsLBCEPJq6DNL8O4ZOJO9+ZpXzsASrhYyBR94KU7WJYy3zM825
          D3xfdiGxtNkaaxSt+v64OyvAQr3wRlH/Cvm671Is74VuHyIhu8/0MKBQHOFYWXDbtELIz
          QBRs/jCAPVlFffpqqiN7cFqp2dBBGJOEkSw4woheHqqyYruajuEdtN3DQ9JvIo=
        - wSkvwofbH9e1ihfkkVQqrLOwDXWCW/dOap8+6NyeLkA7rHt6dylqSQesDIswKM3W4DWTZ
          QGQLeJvCFyVtgSToP1YoiJwnh8ZxK69NzJYbNMCfpPIj154/gG5DpIfeWM/zGwh82WU4u
          4IkJWPza0T/muZ/K/sFPxx2NVCGuT3+k5+vEnoMPDKFVfO2Qk0n2QNm9OXZVKlDgOz938
          JUejK2tUb3wG0rbPeGLg77VcMFIVJ/Ax5gH3zgBKIkF+paelbRtSKdqx0KjnJcRxjR5uA
          nheykJ9c23FYQf8XIVutFgkzlhChIGoao69LQijJVviZZhqxrs7hkINDWUrQ2hnN9et2a
          bFjatHAYDpW3ayyK+r2LDWN4AHN2pEaRUIWY2C8PJMVKpFbep3/gUtwu2OzWwmK6rgSp2
          tFu/5iiVNjRmee36OGm6SWfBNyYYicpHR5sS0orgFw7/44iIYxuLFmZdPlkzRAbht8BtD
          ICFIBXpF8yjJwBi8qA2gZ+NgcEqBDfCgzAM5oyxZaxe+F2LOBg2mqhLlG7r/EfqIWzsFX
          oCzWPGTuuqxbNQ0eQtFaV2RWyQK1NljOvgRhlGDVmHwj0utxH9eAnsV7uLJd3UMwBWooI
          NPjby1DkarFtZHnEZpqLk4Sgp7E8tkuGGmss24PjxM/WSq8fDucPJlKD0HgEa0=
        - AmDvDkqDBqUX2bEcgxtWxxgAdgFHJBGT9o91DZMh1S7dVhguoPhVcw0+gIn17mwxBToSD
          GTkmwYZOR/WQPTcyyyfwxiwfQRNt6Ldsx3GQNO1HKZ3ZIuD7IbYxGSNz/0a/bM+aHYD6H
          UsdqrZ/rfoCUxaiq7vhiYggBNXexAQHLjbtv4rWZWLpXNJiiGPbhIyOn9u9nJPGVrqq9p
          qhTn/BcnNgmojfmxUle4z9et/DUNNl5l13D1INCYqLxcXTLNAPMdgNLcS2kXoFZrr2aKv
          Dj/5OF46bZcdDbkuNhs02ig442UoLxysVmZPi7/ge0JCy7CM9ag0vS5tVfPv/dsYcF6CV
          QJeDGDX7XKCjtf07hpifC1ykMs7FO7yNr8vwJI5Oq89hlYxssHI5P1jq14rtHoJGNP6Ho
          yft1WzpVau2y+u/jF22xIDX5kG36xzwQ2Kry8VwVt9EggE4VuRQjaRyKhXsd0fW9xsN1+
          XZFSKS8eUJziKppEFKskcbAEaUW/jgFE/CqS0PLnk5KecTjt6dANwUHrFUW6cqzCQYT7d
          oLnQqfaot0+851/jopGQlc99X7jWDe6j94dShd92h8KwwZUVmtxMp0sMtcQfCaNmPDytD
          Ch5kl0YZoQo0Du5VpbHOAOJ7ocSkXoiwT6jeU/hxT/N/HwZ4AjKLUG8FfDQr74=
        - yud7o0lXguBoG8LrQZ7Hrtl+5M9o9tcdLYcYXd9pMMfYMuv8BNUWnJRAE0Uj3IiDnqY9n
          EhJn4kM9fYIoBlRGyBcebJP6vMVg2cgS3QKn5VS+JPewihvl7FH3qKQpQVmNUQf1vPUBe
          o7ANNHyUOxKuobp1VpsdbBzqEUyXN69sJCZPowGVO2REjaKr5osjtXh+UmoI7Vs3pY9as
          sm8fJB+uo4nk/b6stW+rBJrUkzpBIgBz7VQ/F9uwxRAotDv3EHfpCD04Owqs0UHS08x8/
          wmPGXL5zgivf3MTG3N0i8fIjcyCNhJKkbRsGaCLxgfR884MnSKg8iZESko4P4CBebsp0k
          EDHHxiNlR7tXv6xADisxwkFv3tvGxje/lhC6zMZkLIVVhLFIwVpFGHkKlP3TS/KH7s/AM
          W6dmvHbVa5r7saSKaZmq0w4MsF1LEiLRDxO+nxkOR7fWDf2Jt6mIDBZ5CT9usgSA3Q0Fs
          xZLMdafgAHFt26GPhk3vgfK+ml+EMOnxTJE3MFS0BLQysoBl1MiVg/umhL5xrHoYNLgjp
          Hie9MDaPR4as3+Inui6391ovYtu1NPJs+p929/BDMJmf3wTunlXgNpuE4NGMB6qSADtmu
          7b1OlagL/2O/mBjL464S+N7GSHQ7CrNcmMN6EmJ7DjrF83uob/I1vuNQH9t2rQ=
        - sq+gKzdM96XYD7bkGOvUtv2ZUWrpn2P9XJlXzZ95zM9/n8Ob4Wik5st4GYY3itW5GNLhi
          HsrORg8IPGj/Feob5BiztCnAEvQRAwJC6o4iciEdXbSltvBMKzjpIW0uVTqJ7WXFCYkKj
          nz8462E9uJ//vPm+6KuXNwDf8jBW2pDhKoyCCMUCX0J3fDJN1BemY4VOXDhEU6E3vjFRZ
          v0kImfVKFlE2+8GH0Zj8DfY84w7BEFDQLfLY2eweavHgIi+5jPjrms1fbBtjenOHASM+s
          8qYvi4aTDCg4CI3QuzfFktnvLKnQM7b0PNTBNspF4hjDhWHgEYCgzJn67y6gUFOtADU75
          O7dDpecnV7po1HTZZmEXPB52eijFB1YfGk/HsPFhNdCN3hetu7gHGN21wIS9cB2npiVXb
          ZT8CaYhO13Hcjt4O3oEmm9Va6/GtwBivfKwK3Roq0s8Ds9C2kxYgYxNT3Ii5hs8H1OXNn
          jKQs939Df8as6OwqUPTVTIOIirkSO8Kt92E1MhOlFqgBhODPQIG3a5fDrbOjrswY7/MjS
          +CSB53ZRDAhydIvZZFuNxMxnkzoATbLQtM2yYc+H2z9hhom+NnZOVjargUJ66gFT63l/c
          dLUAOJz3NSxokvQGcjft1lL0uOfC6L6Lk9ppltKysCGJsOaHl06aC39dJoFjkw=

- job:
    name: clients-tox-bandit
    parent: tox
    description: Run bandit security analysis
    nodeset: debian-bullseye
    vars:
      tox_envlist: bandit

- job:
    name: clients-tox-coverage
    parent: tox
    description: Run all tests with coverage analysis
    nodeset: debian-bullseye
    vars:
      tox_envlist: coverage
    post-run: tests/playbooks/upload-coverage-reports.yaml

- job:
    name: clients-tox-linters-trixie
    parent: openstack-tox-py313
    description: Run linters (Trixie)
    nodeset: debian-trixie-8GB
    vars:
      tox_envlist: linters-trixie
      tox_inline_comments: false

- job:
    name: clients-tox-pep8-trixie
    parent: openstack-tox-py313
    description: Run style checks (Trixie)
    nodeset: debian-trixie-8GB
    vars:
      tox_envlist: pep8-trixie

- job:
    name: clients-tox-bandit-trixie
    parent: openstack-tox-py313
    description: Run bandit security analysis (Trixie)
    nodeset: debian-trixie-8GB
    vars:
      tox_envlist: bandit-trixie

- job:
    name: clients-tox-coverage-trixie
    parent: openstack-tox-py313
    description: Run all tests with coverage analysis (Trixie)
    nodeset: debian-trixie-8GB
    vars:
      tox_envlist: coverage-trixie
    post-run: tests/playbooks/upload-coverage-reports.yaml
